#!/bin/sh

# should only build tags (serverless version) and latest here

docker build --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
    --build-arg VERSION="$CACHE_TAG" \
    -t "$IMAGE_NAME" .
